// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

type Querier interface {
	ChangeEmail(ctx context.Context, arg ChangeEmailParams) (User, error)
	ChangePassword(ctx context.Context, arg ChangePasswordParams) (User, error)
	CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateUser(ctx context.Context, arg DeactivateUserParams) (User, error)
	DeleteReminder(ctx context.Context, arg DeleteReminderParams) error
	GetReminder(ctx context.Context, arg GetReminderParams) (Reminder, error)
	GetReminderConfigs(ctx context.Context, arg GetReminderConfigsParams) (json.RawMessage, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, userID int64) (User, error)
	ListReminders(ctx context.Context, arg ListRemindersParams) ([]Reminder, error)
	SetNewInterval(ctx context.Context, arg SetNewIntervalParams) (Reminder, error)
	SetReminderConfigs(ctx context.Context, arg SetReminderConfigsParams) (Reminder, error)
	UpdateReminder(ctx context.Context, arg UpdateReminderParams) (Reminder, error)
}

var _ Querier = (*Queries)(nil)
